"""add score_history table

Revision ID: a8d0a0574de1
Revises: 57f672c3c624
Create Date: 2026-03-29 03:53:01.186504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d0a0574de1'
down_revision = '57f672c3c624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Удаляем дубликаты (оставляем только последнюю запись для каждой пары user_id + difficulty)
    op.execute("""
        DELETE FROM scores 
        WHERE id NOT IN (
            SELECT MAX(id) 
            FROM scores 
            GROUP BY user_id, difficulty
        )
    """)
    
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Заполняем существующие строки значением по умолчанию
    op.execute("UPDATE scores SET updated_at = '1970-01-01 00:00:00' WHERE updated_at IS NULL")
    
    with op.batch_alter_table('scores', schema=None) as batch_op:
        # Теперь можно безопасно установить NOT NULL
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.create_unique_constraint('uq_user_difficulty', ['user_id', 'difficulty'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('uq_user_difficulty', type_='unique')
        batch_op.drop_column('updated_at')

    op.drop_table('score_history')
    # ### end Alembic commands ###
